site_name: py-canoe
site_url: https://chaitu-ycr.github.io/py-canoe/
site_description: Python 🐍 Package for accessing Vector CANoe 🛶 Tool via COM Interface
site_author: chaitu-ycr

repo_name: ""
repo_url: https://github.com/chaitu-ycr/py-canoe
edit_uri: blob/main/docs/

nav:
  - py_canoe: index.md
  - src_manual: src_manual.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            merge_init_into_class: true
            show_docstring_modules: false
  - include-markdown:
      recursive: true
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search

extra_css:
  - _assets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@11.13.0/dist/mermaid.core.mjs
